PORTNAME=	nv-codec-headers
DISTVERSION=	10.0.26.0
CATEGORIES=	devel

MAINTAINER=	nope@example.org
COMMENT=	FFmpeg version of Nvidia Codec SDK headers

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	FFmpeg
GH_TAGNAME=	n${DISTVERSION}

USES=		gmake

.include <bsd.port.mk>
